# tunnel/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: gestion-produits
data:
  config.yaml: |
    tunnel: e5d3fecb-7eda-4d5c-8d72-1d4a505ca9a5
    credentials-file: /root/.cloudflared/e5d3fecb-7eda-4d5c-8d72-1d4a505ca9a5.json
    ingress:
      - hostname: gestion-produits-mysql.flusin.fr
        service: http://app-mysql.gestion-produits.svc.cluster.local:80
      - hostname: gestion-produits-pgsql.flusin.fr
        service: http://app-pgsql.gestion-produits.svc.cluster.local:80
      - service: http_status:404
