version: "3.3"

services:
  php:
    container_name: gestion-produits-php
    image: gestion-produits-image
    ports:
      - 80:80
  db:
    container_name: gestion-produits-db
    image: mysql:8.4
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql
