apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mysql
  namespace: gestion-produits
spec:
  replicas: 6  # 3 per worker node if 2 nodes
  selector:
    matchLabels:
      app: app-mysql
  template:
    metadata:
      labels:
        app: app-mysql
    spec:
      containers:
        - name: app
          image: ghcr.io/jul-fls/epsi-module-k8s/gestion-produits:latest
          env:
            - name: DB_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: mysql-db
            - name: MYSQL_DB
              value: gestion_produits
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-mysql-secret
                  key: MYSQL_PASSWORD
