apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pgsql
  namespace: gestion-produits
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-pgsql
  template:
    metadata:
      labels:
        app: app-pgsql
    spec:
      containers:
        - name: app
          image: ghcr.io/jul-fls/epsi-module-k8s/gestion-produits:latest
          env:
            - name: DB_TYPE
              value: pgsql
            - name: POSTGRES_HOST
              value: pgsql-db.gestion-produits.svc.cluster.local
            - name: POSTGRES_DB
              value: gestion_produits
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: POSTGRES_PASSWORD