apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-db
  namespace: gestion-produits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-db
  template:
    metadata:
      labels:
        app: pgsql-db
    spec:
      containers:
        - name: pgsql
          image: postgres:17.5
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: PG_ROOT_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: PG_PASSWORD
            - name: POSTGRES_DB
              value: gestion_produits
          volumeMounts:
            - name: pgsql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-init
          configMap:
            name: pgsql-init-script
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-pvc
