apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  namespace: gestion-produits
spec:
  type: LoadBalancer
  selector:
    app: app-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
