apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nolock
    - noatime
    - nfsvers=4.1
  nfs:
    server: 192.168.1.133
    path: /mnt/pool_other/kubernetes/gestion-produits/pgsql
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: gestion-produits
    name: pgsql-data-pgsql-db-0
  storageClassName: manual