apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: gestion-produits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  serviceName: mysql-db-headless
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          envFrom:
            - secretRef:
                name: db-mysql-secret
          env:
            - name: MYSQL_DATABASE
              value: gestion_produits
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init-script
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "manual"  # Replace if needed
        resources:
          requests:
            storage: 1Gi
