apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql-db
  namespace: gestion-produits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-db
  serviceName: pgsql-db-headless
  template:
    metadata:
      labels:
        app: pgsql-db
    spec:
      containers:
        - name: pgsql
          image: postgres:17.5
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: POSTGRES_ROOT_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pgsql-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: gestion_produits
          volumeMounts:
            - name: pgsql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-init
          configMap:
            name: pgsql-init-script
  volumeClaimTemplates:
    - metadata:
        name: pgsql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "manual"  # or your NFS class
        resources:
          requests:
            storage: 1Gi
